import { jsPDF } from 'jspdf';
import { activityHistory } from './activityHistory';

export interface Caption {
  text: string;
  hashtags?: string[];
  platform?: string;
  tone?: string;
  language?: string;
  created_at?: string;
}

// Export to CSV
export const exportToCSV = (captions: Caption[], filename: string = 'captions') => {
  const csvContent = [
    ["Caption", "Hashtags", "Platform", "Tone", "Language", "Created At"],
    ...captions.map((c) => [
      c.text.replace(/\n/g, " ").replace(/"/g, '""'),
      c.hashtags?.join(" ") || "",
      c.platform || "",
      c.tone || "",
      c.language || "",
      c.created_at ? new Date(c.created_at).toLocaleDateString() : "",
    ]),
  ]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  downloadFile(csvContent, `${filename}.csv`, "text/csv");
  
  // Add to activity history
  activityHistory.addExport("CSV", captions.length);
};

// Export to JSON
export const exportToJSON = (captions: Caption[], filename: string = 'captions') => {
  const jsonContent = JSON.stringify(captions, null, 2);
  downloadFile(jsonContent, `${filename}.json`, "application/json");
  
  // Add to activity history
  activityHistory.addExport("JSON", captions.length);
};

// Export to TXT
export const exportToTXT = (captions: Caption[], filename: string = 'captions') => {
  const txtContent = captions
    .map((c, i) => {
      let text = `Caption ${i + 1}:\n${c.text}\n`;
      if (c.hashtags && c.hashtags.length > 0) {
        text += `\nHashtags: ${c.hashtags.map(tag => `#${tag}`).join(" ")}\n`;
      }
      if (c.platform) text += `Platform: ${c.platform}\n`;
      if (c.tone) text += `Tone: ${c.tone}\n`;
      text += "\n" + "=".repeat(50) + "\n\n";
      return text;
    })
    .join("");

  downloadFile(txtContent, `${filename}.txt`, "text/plain");
  
  // Add to activity history
  activityHistory.addExport("TXT", captions.length);
};

// Export to PDF
export const exportToPDF = (captions: Caption[], filename: string = 'captions') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('VidPilot - Saved Captions', margin, yPosition);
  yPosition += 10;

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, margin, yPosition);
  yPosition += 15;

  // Captions
  captions.forEach((caption, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = margin;
    }

    // Caption number
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(`Caption ${index + 1}`, margin, yPosition);
    yPosition += 7;

    // Metadata
    if (caption.platform || caption.tone) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      const metadata = [];
      if (caption.platform) metadata.push(`Platform: ${caption.platform}`);
      if (caption.tone) metadata.push(`Tone: ${caption.tone}`);
      if (caption.language) metadata.push(`Language: ${caption.language}`);
      doc.text(metadata.join(' | '), margin, yPosition);
      yPosition += 7;
    }

    // Caption text
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);
    const lines = doc.splitTextToSize(caption.text, maxWidth);
    doc.text(lines, margin, yPosition);
    yPosition += lines.length * 5 + 5;

    // Hashtags
    if (caption.hashtags && caption.hashtags.length > 0) {
      doc.setFontSize(9);
      doc.setTextColor(50, 100, 200);
      const hashtagText = caption.hashtags.map(tag => `#${tag}`).join(' ');
      const hashtagLines = doc.splitTextToSize(hashtagText, maxWidth);
      doc.text(hashtagLines, margin, yPosition);
      yPosition += hashtagLines.length * 5 + 5;
    }

    // Separator
    doc.setDrawColor(200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;
  });

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by VidPilot - AI Caption Generator', margin, pageHeight - 10);

  doc.save(`${filename}.pdf`);
  
  // Add to activity history
  activityHistory.addExport("PDF", captions.length);
};

// Helper function to download file
const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};
