// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL is missing!');
  console.error('Please add VITE_SUPABASE_URL to your .env file');
  console.error('Example: VITE_SUPABASE_URL=https://your-project.supabase.co');
}

if (!SUPABASE_ANON_KEY) {
  console.error('❌ VITE_SUPABASE_ANON_KEY is missing!');
  console.error('Please add VITE_SUPABASE_ANON_KEY to your .env file');
  console.error('Get it from: Supabase Dashboard → Settings → API');
}

// Validate URL format
const isValidUrl = (url: string | undefined): boolean => {
  if (!url) return false;
  try {
    const urlObj = new URL(url);
    return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
  } catch {
    return false;
  }
};

// Use fallback values if invalid (to prevent app crash)
const validUrl = isValidUrl(SUPABASE_URL) 
  ? SUPABASE_URL 
  : 'https://placeholder.supabase.co';

const validKey = SUPABASE_ANON_KEY || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(validUrl, validKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Show helpful error message if credentials are invalid
if (!isValidUrl(SUPABASE_URL) || !SUPABASE_ANON_KEY) {
  console.warn('⚠️ Supabase credentials are missing or invalid!');
  console.warn('The app will not work properly until you configure .env file');
  console.warn('See CREATE_ENV.md for setup instructions');
}